CREATE TABLE SECURITY
	( EMPLOYEE_ID NUMBER(6,0) CONSTRAINT sec_emp_id_pk PRIMARY KEY,
	  SEC_ID VARCHAR2(20),
	  SEC_PASSWORD VARCAHR2(10),
	  SEC_STATUS CHAR(1),
	  CONSTRAINT sec_emp_fk FOREIGN KEY(EMPLOYEE_ID)
	  	REFERENCES EMPLOYEES(EMPLOYEE_ID) );